### ISSUE TITLE
Design doc for CBO

### ISSUE THREAD

**Issue by satybald** [starburstdata/facebook-presto#38]
I've read an article about work on CBO in [tech](https://www.starburstdata.com/technical-blog/2018/4/2/presto-cost-based-optimizer-rocks-the-tpc-benchmarks) blog. Awesome results folks! I'm wondering if there's a design doc to read about current work on CBO?

**Comment by findepi** [comment]
@satybald we have some internal design documents, but they wouldn't probably be useful without appropriate commentary.
However, we will be describing the key elements on https://www.starburstdata.com/technical-blog/ in coming days.
