### ISSUE TITLE
Unable to read Hive table after loading 

### ISSUE THREAD

**Issue by oliversavio** [starburstdata/facebook-presto#41]
A managed internal table with Bucketing (5 buckets) contains the following files:
`000000_0`
`000001_0`
`000003_0`
`000005_0`

On inserting new records, the files look like this:
`000000_0_copy_1`
`000000_0_copy_2`
`000000_0_copy_3`
`000001_0`
`000003_0`
`000003_0_copy_1`
`000003_0_copy_2`
`000003_0_copy_3`
`000004_0`

This causes Presto to fail, however the [Hive Connector changes](https://docs.starburstdata.com/latest/release/release-0.195-e.html) fixed this issue via  implementing `hive.empty-bucketed-partitions.enabled` and `hive.multi-file-bucketing.enabled`.

I have run into an issue when loading the above table into another via a `CREATE TABLE as SELECT...` statement. Hive renames the files to look like:
`000000_0`
`000001_0`
`000002_0`
`000003_0`
`000004_0`
`000005_0`
`000006_0`
`000007_0`
`000008_0`

This causes the following error `The number of files in the directory (9) does not match the declared bucket count (5) ` .  I assume for a table with 5 buckets, Presto expects the prefix to range from 000000_ to 000004_ and it's the 000005_ to 000008_ prefixes that cause the `PrestoException(HIVE_INVALID_BUCKET_FILES,...)` exception. The table is accessible from Hive and Spark but not via Presto.

As a workaround, if a LIMIT clauses is added to the `CREATE TABLE as SELECT...` statement, it forces hive to create files equal to the number of buckets defined.

**Comment by kokosing** [comment]
Is your table partitioned?

Is `CREATE TABLE as SELECT...` was run via Presto or Hive?

**Comment by oliversavio** [comment]
Nope, the table isn't partitioned.

`CREATE TABLE as SELECT...` was run via Hive

**Comment by kokosing** [comment]
What version of presto are you using? We had a bug related to this which was fixed in 0.195-e.0.8.

**Comment by oliversavio** [comment]
I'm using 0.195-E.0.5, I'll upgrade to 0.195-e.0.8 and get back to you. Thank you.

**Comment by kbajda** [comment]
@oliversavio please let us know whether your issue is gone. if so, let's close this ticket. thanks!

**Comment by oliversavio** [comment]
I haven't been able to verify this. I'll get back to you ASAP.

**Comment by oliversavio** [comment]
Closing this issue since I haven't been able to reproduce it.
