### ISSUE TITLE
Queries getting QUEUED after upgrading to 0.203-e.0.2

### ISSUE THREAD

**Issue by msdotnetclr** [starburstdata/facebook-presto#51]
After upgrading to 0.203-e.0.2, we observed that when there is a query in RUNNING state, all subsequent queries get QUEUED until the first query finishes. We were previously using 0.195-e.0.6 and did not have this problem. The symptom is the same as described in https://github.com/prestodb/presto/issues/10383. Is the change incorporated into Starburst 0.203-e.0.2? 

We do have a very simple resource group configuration file like this:

```json
{
    "rootGroups": [
      {
        "name": "global",
        "softMemoryLimit": "100%",
        "hardConcurrencyLimit": 100,
        "maxQueued": 1000,
        "schedulingPolicy": "weighted",
        "jmxExport": true
      }
    ],
    "selectors": [
      {
        "group": "global"
      }
    ]
  }
```

**Comment by kokosing** [comment]
It looks it was not incorporated. I am working on a new release which will have this.

**Comment by msdotnetclr** [comment]
Thanks, we also observed the same problem as https://github.com/prestodb/presto/pull/9975 in 0.203-e.0.2. Rolling back to 0.195e before these issues can be addressed.

**Comment by syvineckruyk** [comment]
is rolling back the only immediate solve for this issue ? .. just upgraded from 0.167 if so I have not been able to find downloads for 0.195e ... anyone have a working link ?

**Comment by mnoumanshahzad** [comment]
Could someone kindly provide more context about resource groups? I have upgraded from 0.194 to 0.203 and haven't set-up a resource group configurations, is it mandatory now?

I am facing the same issue as @msdotnetclr. "when there is a query in RUNNING state, all subsequent queries get QUEUED until the first query finishes"

How can I remedy this problem?

Thanks

**Comment by msdotnetclr** [comment]
Muhanmmad, the fix is very easy (see here
https://github.com/prestodb/presto/pull/10789/commits/bf503fad642af7caa55336d17c3d3e08c43fb88a),
however it seems that Starburst has not published the 0.203-e.0.2 branch in
Github, you can't simply create your own build to address the issue.

**Comment by kokosing** [comment]
The fixes were incorporated in 0.203-e.0.5.

**Comment by msdotnetclr** [comment]
@kokosing which branch/tag should I pull to get 0.203-e.0.5?

**Comment by mattsfuller** [comment]
0.203-e.0.7, which incorporates these changes, is available for download now from Starburst's website. You can find the release notes here:
https://docs.starburstdata.com/latest/release/release-0.203-e.html#release-0-203-e-0-5
